[package]
name = "session-code-router"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../../common/common" }

[[bin]]
name = "session-code-router"
path = "bin/main.rs"
bench = false
doctest = false
test = false
