[package]
name = "uniswap-v2-library"
version = "0.2.0"
authors = ["Muhammad Adrees <muhammad.adrees@scytalelabs.com>"]
edition = "2018"

[dependencies]
common = { path = "../../common/common" }

[[bin]]
name = "uniswap-v2-library"
path = "bin/uniswap.rs"
bench = false
doctest = false
test = false